### ISSUE TITLE
[Suggestion]: Minor UX Issues

### ISSUE THREAD

**Issue by clavery** [sfccdevops/sfcc-docs#2]
### Issue Checklist:

- [X] There are no matching [Open Feature Requests](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Feature+Request"+is%3Aopen)
- [X] There are no matching [Closed Feature Requests](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Feature+Request"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### Suggestion / Feature Request

Some minor UX suggestions:

1. Might want to clarify that it's for the Script/Pipelet/Jobstep APIs. Only because (right now) it doesn't include the SCAPI, OCAPI, Guides, etc. And maybe a small section on the index for links to the (various) official ones. Would be helpful for SEO too. (actually now I see you have a button to the github.io docs, that's good. Other links to docs not covered might still be good though)
2. Left navigation groups looks alphabetical but script API first might be slightly better since that's 90% of the queries (and because it's below the fold). (also does the search sort this way? that might be more important to put script API first).
3. Is there a way to input a search query from URL? For instance on devdocs.io you can search arbitrarily with this form: `https://devdocs.io/#q=head`. Thinking folks can set up a custom search shortcut in chrome for the site, type `sfccdocs[TAB]order` and land on a search for `order`. Might be a cool selling point for searching right in your browser bar.
4. I think the site looks best at 110% scaled in terms of fonts, etc (but this is probably my bad eyesight and I think I sunburned my eyeballs today).
5. Version switcher z-index is behind the main content
6. Search and filter boxes could use a slight debounce. When typing fast it seems to execute the search but a debounce on the filtering would allow for lots of keystrokes without lag.
7. nit: the right nav on script APIs could probably use types or something in the methods. When there is a method overload you get a lot of repitition in the names (like on the `Mac` class you see digest, diest, digest. Obviously there's limited space here.

**Comment by manifestinteractive** [comment]
@clavery Responses for the reported issues:

1. Would there be interest in having those missing docs here? I have them, I honestly just did not use them so thought maybe others might not need them either.  But happy to put them back in.
2. I agree, and have reversed the order for this first parent listing ( new order will be Script, Pipelet & Job Step ).  This will be shipped in the next repease.
3. This is a really good idea.  I will look into getting this added.  Since there is no traditional search results page, who would you envision this working? e.g. would we just reload the search tool on page load if a query exists in the hash?
4. If it's still an issue, let me know.  Could be a cool option to allow that to be configured like themes.  People will want different sizes more than likely,  This is just Tailwind CSS default sizing.
5. I've fixed the z-index issues and will have that out in the next release.
6. I had a debounce on here, and because of react's state management, it actually felt more laggy with the debounce, but I can give it a go again.
7. That right nav is auto generated from headings, but I can take a look at trying to do things more dynamically

**Comment by manifestinteractive** [comment]
@clavery 2 & 5 in your list above were deployed in v0.2.0 release that went out today.  Your number 4 also got a slight fix in the menu, as I went ahead and bumped that up as it was pretty small.

**Comment by clavery** [comment]
3. Good question and yes I think that solution makes sense. For other SPA type apps this is kinda how it works. For instance swagger-UI will load and if an endpoint exists in the hash it opens and scrolls to it. Maybe the search can be handled via next URL state or maybe it's just a special case to look for it on load and open the search? (or maybe even an option to have a traditional search results page in addition to the popover search.
4. I can zoom. It looks fine.
5. .
6. Yeah feels laggy at high typing speed but it's a minor issue overall.
7. It's a pretty minor thing.

**Comment by manifestinteractive** [comment]
@clavery  

## Item 3 

in your list I have added support for `/?q=<keyword>`

You this will load the search engine, do a search and go to the first result.

Future versions I may hide the search panel and just keep the page blurred with like a loading page as it feels a bit weird.  But it works.  I like this idea as now anyone can just send a link to these docs with a keyword attached via `https://sfccdocs.com/?q=<keyword>`

https://sfccdocs.com/?q=normalize

## Item 6

I've added a 150ms debounce to typing.  I also fixed a bug with non-alphanumeric inputs ( like control characters ) that were incorrectly hiding results until you typed again )

## Item 7

This has also been resolved

**Comment by manifestinteractive** [comment]
Closing this out since everything in here is fixed that was a bug or UX/UI issue
