### ISSUE TITLE
Search Suggestions display Class description rather than Method description

### ISSUE THREAD

**Issue by sholsinger** [sfccdevops/sfcc-docs#21]
### Issue Checklist:

- [X] No matching [Open Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aopen)
- [X] No matching [Closed Bugs](https://github.com/sfccdevops/sfcc-docs/issues?q=is%3Aissue+label%3A"Bug+Report"+is%3Aclosed)
- [X] I've read the [Contributing Guide](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CONTRIBUTING.md)
- [X] I'm following the [Code of Conduct](https://github.com/sfccdevops/sfcc-docs/blob/develop/.github/CODE_OF_CONDUCT.md)

### What happened?

While testing #8 I noticed that the descriptions shown in the typeahead search are the class descriptions instead of the methods which are being presented.

<img width="581" alt="Screenshot 2023-09-20 at 4 34 38 PM" src="https://github.com/sfccdevops/sfcc-docs/assets/435501/335a4f63-42b9-43a5-847b-dab6aea03241">

Expected outcome is that the method's description (if available) would be displayed instead of the class description.

### Which Browser(s) were you using?

Impacts All

### Which Operating System(s) were you using?

Impacts All

### Steps to produce this issue.

1. Navigate to https://sfccdocs.com/
2. Type: `setTracking`

**Comment by manifestinteractive** [comment]
This one is not really possible due to how the indexing works.  The search results that do have a full index can find the match, but not descriptions about those matches.

**Comment by manifestinteractive** [comment]
@sholsinger reopening this as I think I figured out a solution.  Not exactly what you are asking for, but way more helpful than not. Turns out I can grab the first few lines from the section that the resulting match was found in ( does mean I have to store that in the index, but if it's just the first line, it's not too bad.

Here's what it ends up looking like.  Let me know if this is good enough for you for this ticket :) 

This new data is the second line of each result, the first line is the page description.  In some instances the result is for the entire page and not for a section, so for those instances, there won't be a second line in the search results.

![Screenshot 2023-11-01 at 5 36 40 AM](https://github.com/sfccdevops/sfcc-docs/assets/508411/f17240de-00e4-4433-8178-0419b6e9db3d)

**Comment by manifestinteractive** [comment]
@sholsinger I can also go with the second line as it does look like most of the time, that is the description ... but ya, it's just a balance of storing more text in the indexer, but here is what that second line looks like for the same query

![Screenshot 2023-11-01 at 5 28 34 AM](https://github.com/sfccdevops/sfcc-docs/assets/508411/a3c349b1-38fa-4f57-bbba-80815e10cde3)

**Comment by sholsinger** [comment]
You're awesome!

**Comment by manifestinteractive** [comment]
This was deployed in release 0.6.0
